default_language_version:
  node: 17.9.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [-l 120]
        additional_dependencies: ["click==8.0.4"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, -l, "120", --lines-after-imports, "2"]

  - repo: https://git.evocargo.org/thirdparty/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8 (py3)
        args:
          [--max-line-length=120, "--ignore=E203,E231,W503,E266,B301,B028,E402"]
        additional_dependencies: [flake8-bugbear]
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        args: [--print-width=80, --prose-wrap=always]
